/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109048-g65f3bc9e7e-20221110"
#endif /* AVUTIL_FFVERSION_H */
